import * as XLSX from 'xlsx';
import { AIAnalysisResult, UserSegment, Transaction } from '../types';

/**
 * Parse AI analysis Excel files back into data structures
 * Reads the Excel files generated by AnalysisExcelGenerator
 */
export class AnalysisExcelParser {
  /**
   * Parse the uploaded AI analysis Excel file
   */
  async parseAnalysisExcel(filePath: string): Promise<Partial<AIAnalysisResult>> {
    const workbook = XLSX.readFile(filePath);

    const result: Partial<AIAnalysisResult> = {};

    // Parse Sheet 1: User Segments
    const segmentSheetName = '1_사용자_세그먼트';
    if (workbook.SheetNames.includes(segmentSheetName)) {
      result.userSegments = this.parseUserSegments(workbook.Sheets[segmentSheetName]) as any;
      result.sessionPatterns = this.parseSessionPatterns(workbook.Sheets[segmentSheetName]);
    }

    // Parse Sheet 2: Event Sequencing (partial - complex structure)
    const sequencingSheetName = '2_이벤트_순서_규칙';
    if (workbook.SheetNames.includes(sequencingSheetName)) {
      result.eventSequencing = this.parseEventSequencing(workbook.Sheets[sequencingSheetName]);
    }

    // Parse Sheet 3: Transactions (if exists)
    const transactionSheetName = '3_트랜잭션_정의';
    if (workbook.SheetNames.includes(transactionSheetName)) {
      const transactions = this.parseTransactions(workbook.Sheets[transactionSheetName]);
      if (result.eventSequencing) {
        result.eventSequencing.transactions = transactions;
      } else {
        result.eventSequencing = { transactions } as any;
      }
    }

    return result;
  }

  /**
   * Parse user segments from sheet 1
   */
  private parseUserSegments(sheet: XLSX.WorkSheet): UserSegment[] {
    const data: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });
    const segments: UserSegment[] = [];

    // Find the header row (contains "세그먼트명")
    let headerRowIndex = -1;
    for (let i = 0; i < data.length; i++) {
      if (data[i]?.includes('세그먼트명')) {
        headerRowIndex = i;
        break;
      }
    }

    if (headerRowIndex === -1) {
      console.warn('⚠️ User segment header not found');
      return [];
    }

    // Parse data rows (skip header)
    for (let i = headerRowIndex + 1; i < data.length; i++) {
      const row = data[i];

      // Stop at empty rows or footer
      if (!row || row.length === 0 || row[0]?.toString().startsWith('💡')) {
        break;
      }

      const name = row[0]?.toString();
      const ratioPercent = parseFloat(row[1]?.toString() || '0');
      const characteristics = row[2]?.toString() || '';

      if (name && !isNaN(ratioPercent)) {
        segments.push({
          name,
          ratio: ratioPercent / 100, // Convert percentage to decimal
          characteristics
        });
      }
    }

    console.log(`📊 Parsed ${segments.length} user segments`);
    return segments;
  }

  /**
   * Parse session patterns from sheet 1
   */
  private parseSessionPatterns(sheet: XLSX.WorkSheet): any {
    const data: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });
    const patterns: any = {
      avgSessionsPerDay: {},
      avgSessionDuration: {},
      avgEventsPerSession: {}
    };

    // Find the header row
    let headerRowIndex = -1;
    for (let i = 0; i < data.length; i++) {
      if (data[i]?.includes('세그먼트명')) {
        headerRowIndex = i;
        break;
      }
    }

    if (headerRowIndex === -1) {
      return patterns;
    }

    // Parse data rows
    for (let i = headerRowIndex + 1; i < data.length; i++) {
      const row = data[i];

      if (!row || row.length === 0 || row[0]?.toString().startsWith('💡')) {
        break;
      }

      const name = row[0]?.toString();
      if (!name) continue;

      patterns.avgSessionsPerDay[name] = parseFloat(row[3]?.toString() || '0');
      patterns.avgSessionDuration[name] = parseFloat(row[4]?.toString() || '0') * 1000 * 60; // Convert minutes to ms
      patterns.avgEventsPerSession[name] = parseInt(row[5]?.toString() || '0');
    }

    return patterns;
  }

  /**
   * Parse event sequencing from sheet 2 (simplified version)
   */
  private parseEventSequencing(sheet: XLSX.WorkSheet): any {
    const data: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });

    const sequencing: any = {
      eventCategories: {},
      strictDependencies: {},
      executionConstraints: {},
      logicalSequences: []
    };

    // Parse event categories
    let inCategorySection = false;
    let inDependencySection = false;
    let inConstraintSection = false;

    for (let i = 0; i < data.length; i++) {
      const row = data[i];
      if (!row || row.length === 0) continue;

      const firstCell = row[0]?.toString() || '';

      // Detect sections
      if (firstCell.includes('이벤트 카테고리')) {
        inCategorySection = true;
        inDependencySection = false;
        inConstraintSection = false;
        i++; // Skip header row
        continue;
      } else if (firstCell.includes('필수 선행 이벤트')) {
        inCategorySection = false;
        inDependencySection = true;
        inConstraintSection = false;
        i++; // Skip header row
        continue;
      } else if (firstCell.includes('실행 제약')) {
        inCategorySection = false;
        inDependencySection = false;
        inConstraintSection = true;
        i++; // Skip header row
        continue;
      } else if (firstCell.startsWith('💡')) {
        break; // End of data
      }

      // Parse based on current section
      if (inCategorySection) {
        const category = row[0]?.toString();
        const events = row[1]?.toString().split(',').map((e: string) => e.trim()).filter(Boolean);
        if (category && events.length > 0) {
          sequencing.eventCategories[category] = events;
        }
      } else if (inDependencySection) {
        const event = row[0]?.toString();
        const deps = row[1]?.toString().split(',').map((d: string) => d.trim()).filter(Boolean);
        if (event && deps.length > 0) {
          sequencing.strictDependencies[event] = deps;
        }
      } else if (inConstraintSection) {
        const event = row[0]?.toString();
        const constraintType = row[1]?.toString();
        const constraintValue = row[2];

        if (event && constraintType) {
          if (!sequencing.executionConstraints[event]) {
            sequencing.executionConstraints[event] = {};
          }

          if (constraintType.includes('세션당 최대 횟수')) {
            sequencing.executionConstraints[event].maxOccurrencesPerSession = parseInt(constraintValue?.toString() || '0');
          } else if (constraintType.includes('유저당 최대 횟수')) {
            sequencing.executionConstraints[event].maxOccurrencesPerUser = parseInt(constraintValue?.toString() || '0');
          } else if (constraintType.includes('첫 세션 전용')) {
            sequencing.executionConstraints[event].requiresFirstSession = true;
          } else if (constraintType.includes('차단 규칙')) {
            const blockedEvents = constraintValue?.toString().split(',').map((e: string) => e.trim()).filter(Boolean);
            sequencing.executionConstraints[event].blockedAfterEvents = blockedEvents;
          }
        }
      }
    }

    console.log(`📊 Parsed event sequencing:`, {
      categories: Object.keys(sequencing.eventCategories).length,
      dependencies: Object.keys(sequencing.strictDependencies).length,
      constraints: Object.keys(sequencing.executionConstraints).length
    });

    return sequencing;
  }

  /**
   * Parse transactions from sheet 3
   */
  private parseTransactions(sheet: XLSX.WorkSheet): Transaction[] {
    const data: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });
    const transactions: Transaction[] = [];

    // Find the header row
    let headerRowIndex = -1;
    for (let i = 0; i < data.length; i++) {
      if (data[i]?.includes('트랜잭션명')) {
        headerRowIndex = i;
        break;
      }
    }

    if (headerRowIndex === -1) {
      console.warn('⚠️ Transaction header not found');
      return [];
    }

    // Parse data rows
    for (let i = headerRowIndex + 1; i < data.length; i++) {
      const row = data[i];

      if (!row || row.length === 0 || row[0]?.toString().startsWith('💡') || row[0]?.toString().startsWith('예시')) {
        break;
      }

      const name = row[0]?.toString();
      const description = row[1]?.toString() || '';
      const startEvents = row[2]?.toString().split(',').map((e: string) => e.trim()).filter(Boolean) || [];
      const endEvents = row[3]?.toString().split(',').map((e: string) => e.trim()).filter(Boolean) || [];
      const innerEvents = row[4]?.toString().split(',').map((e: string) => e.trim()).filter(Boolean) || [];
      const allowInnerAfterEnd = row[5]?.toString().includes('허용');

      if (name && startEvents.length > 0 && endEvents.length > 0) {
        transactions.push({
          name,
          description,
          startEvents,
          endEvents,
          innerEvents,
          allowInnerAfterEnd
        });
      }
    }

    console.log(`📊 Parsed ${transactions.length} transactions`);
    return transactions;
  }
}
